version: '2'
services:
  consul:
    image: consul:latest
    command: consul agent -dev -client 0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  service:
    build: service
    links:
     - consul
    environment:
      # Note how easily we can overwrite Spring Boot's configuration parameters from the application.properties file via environment variables
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_PROFILES_ACTIVE: docker
  ui:
    build: ui
    links:
     - consul
    ports:
     - "8090:8090"
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_PROFILES_ACTIVE: docker